default_context:
  project_name: 'Full Stack FastAPI MongoDB'
  project_slug: 'full-stack-fastapi-mongodb'
  domain_main: 'localhost.tiangolo.com'
  domain_staging: 'stag.localhost.tiangolo.com'
  domain_base_api_url: 'http://localhost.tiangolo.com/api/v1'
  domain_base_ws_url: 'ws://localhost.tiangolo.com/api/v1'
  docker_swarm_stack_name_main: 'localhost-tiangolo-com'
  docker_swarm_stack_name_staging: 'stag-localhost-tiangolo-com'
  secret_key: 'Gvas0auGUMD33qsotcGIQnONZPcQVeNlR0YQhTevjZA'
  first_superuser: 'admin@localhost.tiangolo.com'
  first_superuser_password: 'MyAppAdmin@2026#Secure'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.localhost.tiangolo.com", "https://stag.localhost.tiangolo.com", "https://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@localhost.tiangolo.com'
  smtp_emails_from_name: 'Full Stack FastAPI MongoDB'
  smtp_emails_to_email: 'info@localhost.tiangolo.com'
  mongodb_uri: 'mongodb'
  mongodb_database: 'app'
  traefik_constraint_tag: 'localhost.tiangolo.com'
  traefik_constraint_tag_staging: 'stag.localhost.tiangolo.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'floweradmin:Flower@2026#Secure'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
